name:                tasty-hiounit
version:             0.1.3
github:              "githubuser/tasty-hiounit"
license:             BSD-3-Clause
author:              "Jörg K.-H. W. Brüggmann"
maintainer:          "info@joerg-brueggmann.de"
copyright:           "2023-2024 Jörg K.-H. W. Brüggmann"

extra-source-files:
- README.md

extra-doc-files:
- CHANGELOG.md

# Metadata used when publishing your package
synopsis: >
  A test provider for the test framework *tasty* for unit tests 
  of IO functions.
category:            Testing

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/tasty-hiounit#readme>

dependencies:
- base >= 4.7 && < 5
- directory >= 1.3.7 && < 1.4
- template-haskell >= 2.19.0 && < 2.20
- ghc >= 9.4.8 && < 9.5
- process >= 1.6.18 && < 1.7
- ghc-paths >= 0.1.0 && < 0.2
- safe-exceptions >= 0.1.7 && < 0.2
- tasty >= 1.5 && < 1.6
- tasty-hunit >= 0.10.1 && < 0.11
- tasty-quickcheck >= 0.10.3 && < 0.11

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  hdynexec:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tasty-hiounit

tests:
  tasty-hiounit-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tasty-hiounit
