name:                tasty-hiounit
version:             0.1.2
github:              "githubuser/tasty-hiounit"
license:             BSD-3-Clause
author:              "Jörg K.-H. W. Brüggmann"
maintainer:          "info@joerg-brueggmann.de"
copyright:           "2023-2024 Jörg K.-H. W. Brüggmann"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/tasty-hiounit#readme>

dependencies:
- base >= 4.7 && < 5
- safe-exceptions
- ghc
- ghc-paths
- directory
- process
- tasty
- tasty-hunit
- tasty-quickcheck
- tasty-hunit
- template-haskell

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  hdynexec:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tasty-hiounit

tests:
  tasty-hiounit-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tasty-hiounit
